ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/alsps/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/hwmon/include
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/sensorHub/inc_v1
ccflags-y += -I$(srctree)/drivers/misc/mediatek/scp/$(CONFIG_MTK_PLATFORM)
# begin, prize-lifenfen-20181126, add for sensorhub hardware info
ccflags-y += -I$(srctree)/drivers/misc/mediatek/hardware_info
# end, prize-lifenfen-20181126, add for sensorhub hardware info
obj-y	:=  alspshub.o

