obj-$(CONFIG_PRIZE_AUDIO) += audio/
obj-$(CONFIG_PRIZE_FP) += fp/
obj-$(CONFIG_PRIZE_LCD_BIAS) += lcdbias/
obj-$(CONFIG_PRIZE_TOUCHKEY) += touchkey/
obj-$(CONFIG_PRIZE_CAMERA) += camera/
obj-$(CONFIG_PRIZE_SCREEN_STATE) += screen_state/
obj-$(CONFIG_PRIZE_LED) += led/
obj-$(CONFIG_PRIZE_VEB_A5) += veb_a5spi_driver/