#
# Makefile for all kinds of Fingerprint
#

obj-$(CONFIG_GOODIX_FINGERPRINT) += goodix/
obj-$(CONFIG_FPC_FINGERPRINT) += fpc/
obj-$(CONFIG_MTK_FINGERPRINT_SUNWAVECORP) += sunwave_driver_all_in_one/
#prize-add finger-pengzhipeng-20190419-start
obj-$(CONFIG_FT9362_FINGERPRINT) += focaltech/
obj-$(CONFIG_FT9362_FINGERPRINT_TEE) += focaltech_tee/
obj-$(CONFIG_MICROARRAY_FINGERPRINT) += microarray_fp/
obj-$(CONFIG_PRIZE_FP_FPSENSOR_REE) += fpsensor_ree/
#prize-add finger-pengzhipeng-20190419-end
#prize add by lipengpeng 20191203 start 
obj-$(CONFIG_BETTERLIFE_FINGERPRINT) += betterlife_fp/
#prize add by lipengpeng 20191203 end