#
# Makefile for all kinds of Fingerprint
#
obj-$(CONFIG_SUNWAVE_TEE_FINGERPRINT) += sunwave_fp_tee/
obj-$(CONFIG_GOODIX_FINGERPRINT) += goodix/
obj-$(CONFIG_FPC_FINGERPRINT) += fpc/
#prize-add-pengzhipeng-20191105-start
#prize add by lipengpeng 20191217 start 
obj-$(CONFIG_SUNWAVE_FINGERPRINT) += sunwave_driver_all_in_one/
#prize add by lipengpeng 20191217 end
obj-$(CONFIG_FT9362_FINGERPRINT) += focaltech/
obj-$(CONFIG_FT9362_FINGERPRINT_TEE) += focaltech_tee/
obj-$(CONFIG_MTK_FINGERPRINT_SUNWAVECORP) += sunwave_driver_all_in_one/
obj-$(CONFIG_MICROARRAY_FINGERPRINT) += microarray_fp/
#prize-add-pengzhipeng-20191105-end
