
# Makefile for misc devices that really don't fit anywhere else.
#

obj-y += hct_ft8716f_fhdliuhai_dsi_vdo_auo_618.o
ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc
ccflags-$(CONFIG_PRIZE_LCD_BIAS_TPS65132) += -I$(srctree)/drivers/misc/mediatek/prize/lcdbias/tps65132



