#
# Makefile for misc devices that really don't fit anywhere else.
#
#prize-add tp enter low power mode-pengzhipeng-20190109-start
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/focaltech_touch_V3
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/
#prize-add tp enter low power mode-pengzhipeng-20190109-end

obj-y += ft8006p_hdp_dsi_vdo_tm6217_drip_incell.o




